# CMake generated Testfile for 
# Source directory: /home/ued520/makefile_ninja_benchmarks/llama.cpp/examples
# Build directory: /home/ued520/makefile_ninja_benchmarks/llama.cpp/make_build/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("batched-bench")
subdirs("batched")
subdirs("embedding")
subdirs("eval-callback")
subdirs("gbnf-validator")
subdirs("gguf-hash")
subdirs("gguf-split")
subdirs("gguf")
subdirs("gritlm")
subdirs("imatrix")
subdirs("infill")
subdirs("llama-bench")
subdirs("lookahead")
subdirs("lookup")
subdirs("main")
subdirs("parallel")
subdirs("passkey")
subdirs("perplexity")
subdirs("quantize")
subdirs("retrieval")
subdirs("server")
subdirs("save-load-state")
subdirs("run")
subdirs("simple")
subdirs("simple-chat")
subdirs("speculative")
subdirs("speculative-simple")
subdirs("tokenize")
subdirs("tts")
subdirs("gen-docs")
subdirs("convert-llama2c-to-ggml")
subdirs("cvector-generator")
subdirs("export-lora")
subdirs("quantize-stats")
subdirs("llava")
