# CMake generated Testfile for 
# Source directory: /home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests
# Build directory: /home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/build_ninja/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test1 "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test1.test")
set_tests_properties(test1 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test2 "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test2.test")
set_tests_properties(test2 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test4 "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test4.test")
set_tests_properties(test4 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(testReplaceExisting "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/testReplaceExisting.test")
set_tests_properties(testReplaceExisting PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_cast "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_cast.test")
set_tests_properties(test_cast PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_charcase "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_charcase.test")
set_tests_properties(test_charcase PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_compare "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_compare.test")
set_tests_properties(test_compare PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_deep_copy "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_deep_copy.test")
set_tests_properties(test_deep_copy PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_double_serializer "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_double_serializer.test")
set_tests_properties(test_double_serializer PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_float "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_float.test")
set_tests_properties(test_float PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_int_add "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_int_add.test")
set_tests_properties(test_int_add PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_int_get "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_int_get.test")
set_tests_properties(test_int_get PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_locale "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_locale.test")
set_tests_properties(test_locale PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_null "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_null.test")
set_tests_properties(test_null PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_parse "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_parse.test")
set_tests_properties(test_parse PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_parse_int64 "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_parse_int64.test")
set_tests_properties(test_parse_int64 PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_printbuf "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_printbuf.test")
set_tests_properties(test_printbuf PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_set_serializer "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_set_serializer.test")
set_tests_properties(test_set_serializer PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_set_value "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_set_value.test")
set_tests_properties(test_set_value PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_strerror "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_strerror.test")
set_tests_properties(test_strerror PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_util_file "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_util_file.test")
set_tests_properties(test_util_file PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_visit "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_visit.test")
set_tests_properties(test_visit PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_object_iterator "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_object_iterator.test")
set_tests_properties(test_object_iterator PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_json_pointer "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_json_pointer.test")
set_tests_properties(test_json_pointer PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
add_test(test_json_patch "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/test_json_patch.test")
set_tests_properties(test_json_patch PROPERTIES  _BACKTRACE_TRIPLES "/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;50;add_test;/home/ubuntu/Xinrui/makefile_ninja_benchmarks/json-c/tests/CMakeLists.txt;0;")
